# Numpy Exercises

##### Exercícios do curso Data Analysis with Python (freeCodeCamp)

Disponível em: <a href="https://github.com/ine-rmotr-curriculum/freecodecamp-intro-to-numpy/blob/master/3.%20NumPy%20exercises.ipynb" target="_blank">github</a>

<hr style="margin-bottom: 40px;">

### Array creation

In [2]:
import numpy as np

In [5]:
# Create a numpy array of size 10, filled with zeros

a = np.zeros ((10,10))
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
# Create a numpy array with values ranging from 10 to 49

b = np.arange (10,50)
print (b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
# Create a numpy matrix of 2*2 integers, filled with ones

c = np.ones ((2,2), dtype = 'int')
print (c)

[[1 1]
 [1 1]]


In [21]:
# Create a numpy matrix of 3*2 float numbers, filled with ones

d = np.ones ((3,2), dtype = 'float')
print (d)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones

e = np.ones (a.shape)
print (e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [27]:
# Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones -- solution 2

f = np.ones_like (a)
print (f)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

h = np.random.rand(2,3)
print (h)

h1 = np.zeros_like (h)
print (h1)

[[0.39503857 0.59133916 0.4882248 ]
 [0.11400555 0.84583077 0.37437501]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [38]:
# Create a numpy matrix of 4*4 integers, filled with fives

i = 5 * np.ones ((4,4), dtype = np.int)
print (i)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [42]:
# Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens

# np.random.randint (min, max, size = (rows, columns)) -- random integer

j = np.random.randint (-4,10, size = (5,8))
print (j)

j1 = 7 * np.ones_like (j)
print (j1)

[[ 5  2  7  2  9  1  7  6]
 [ 4  3 -1  3 -3 -3  1 -4]
 [ 1  4  4  8 -1 -3  2 -4]
 [-1  8  0  1 -1  3  6  3]
 [-4  9  4  1 -3  3  1 -4]]
[[7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]]


In [45]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere

k = np.identity (3)
print (k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
# Create a numpy array, filled with 3 random integer values between 1 and 10

l = np.random.randint (1, 11, size = 3)
print (l)

[2 6 2]


In [58]:
# Create a 3*3*3 numpy matrix, filled with random float values

m = np.random.randn (3,3,3)
print (m)

print (' ')

m1 = np.random.random ((3,3,3))
print (m1)

[[[-0.94010897 -0.22459141 -0.68517838]
  [ 0.32679824  0.22059638 -1.70463158]
  [-0.6167373   1.34566817 -2.00101109]]

 [[ 0.87836868 -2.35303981 -1.47255596]
  [ 0.55889066  0.38937103 -0.40951346]
  [-0.33554794 -0.15195143 -0.02878981]]

 [[ 0.88113958  0.36364771  0.24671927]
  [ 0.03832005  0.7156653   0.79364549]
  [-0.2494255   0.52537165  0.84331697]]]
 
[[[0.69676954 0.67389488 0.23817591]
  [0.99815918 0.50393322 0.19055251]
  [0.44360176 0.82255209 0.05990095]]

 [[0.92703812 0.4611088  0.74774806]
  [0.55229518 0.16510565 0.96879132]
  [0.18882708 0.24637234 0.16676087]]

 [[0.88239495 0.74085961 0.01935733]
  [0.36182682 0.77894326 0.50339382]
  [0.52717453 0.9828812  0.35883984]]]


In [60]:
# Given the X python list convert it to an Y numpy array

lista = [1, 2, 3, 4, 5]
print (lista, type(lista))

listarray = np.array (lista)
print (listarray, type(listarray))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [73]:
# Given the X numpy array, make a copy and store it on Y

n = np.random.randint (10, size = (3,4,5))
print ("n: \n",n, "\n\n")

n1 = np.copy (n)
print ("cópia de n: \n", n1, "\n\n")

n1 [2,1,1] = 1000
print ('Alterado o valor da posição (2,1,1) para 1000')
print ("n: \n", n, "\n\n")
print ("cópia de n: \n", n1)

n: 
 [[[7 4 1 6 3]
  [4 3 4 0 6]
  [8 9 8 3 6]
  [1 2 7 9 1]]

 [[0 6 1 4 3]
  [2 7 5 7 4]
  [3 2 3 6 4]
  [8 1 4 8 2]]

 [[2 1 7 2 1]
  [0 3 1 7 4]
  [0 3 5 9 9]
  [2 4 0 2 8]]] 


cópia de n: 
 [[[7 4 1 6 3]
  [4 3 4 0 6]
  [8 9 8 3 6]
  [1 2 7 9 1]]

 [[0 6 1 4 3]
  [2 7 5 7 4]
  [3 2 3 6 4]
  [8 1 4 8 2]]

 [[2 1 7 2 1]
  [0 3 1 7 4]
  [0 3 5 9 9]
  [2 4 0 2 8]]] 


Alterado o valor da posição (2,1,1) para 1000
n: 
 [[[7 4 1 6 3]
  [4 3 4 0 6]
  [8 9 8 3 6]
  [1 2 7 9 1]]

 [[0 6 1 4 3]
  [2 7 5 7 4]
  [3 2 3 6 4]
  [8 1 4 8 2]]

 [[2 1 7 2 1]
  [0 3 1 7 4]
  [0 3 5 9 9]
  [2 4 0 2 8]]] 


cópia de n: 
 [[[   7    4    1    6    3]
  [   4    3    4    0    6]
  [   8    9    8    3    6]
  [   1    2    7    9    1]]

 [[   0    6    1    4    3]
  [   2    7    5    7    4]
  [   3    2    3    6    4]
  [   8    1    4    8    2]]

 [[   2    1    7    2    1]
  [   0 1000    1    7    4]
  [   0    3    5    9    9]
  [   2    4    0    2    8]]]


In [77]:
# Create a numpy array with numbers from 1 to 10

o = np.arange (1,11)
print (o)

[ 1  2  3  4  5  6  7  8  9 10]


In [78]:
# Create a numpy array with the odd numbers between 1 to 10

p = np.arange (1,10,2)
print (p)

[1 3 5 7 9]


In [90]:
# Create a numpy array with numbers from 1 to 10, in descending order

q = np.arange (10,0,-1)
print (q)

q1 = np.arange (1,11) [::-1]
print (q1)

[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


In [93]:
# Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

# random values
r = np.random.randint (0, 8, size = (3,3) )
print (r,"\n")

# sequencial 
r1 = np.arange (9).reshape (3,3)
print (r1)

[[6 3 3]
 [4 4 3]
 [7 7 7]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [103]:
# Show the memory size of the given Z numpy matrix

print (r1.size * r1.itemsize)

36


<hr style="margin-bottom: 40px;">

### Array indexation

In [137]:
# Given the X numpy array, show it's first element

aa = np.random.randint (0, 50, 33)
print (aa)
aa [0]

[ 4  8 25 17 11 13  9 36  9 32 27 10 18 43 47 30 30 31  7 43  2 37 22 30
 46 41 46 32 16 27 42  5 27]


4

In [115]:
# Given the X numpy array, show it's last element

aa [-1,-1]

13

In [132]:
# Given the X numpy array, show it's first three elements

ab = np.random.randint (0, 50, 15)
print (ab)

ab [0:3]

[28 34  7  2  4  2 24 21 32 49 41  6 10 27 43]


array([28, 34,  7])

In [134]:
# Given the X numpy array, show all middle elements

ab [1:-1]

array([34,  7,  2,  4,  2, 24, 21, 32, 49, 41,  6, 10, 27])

In [135]:
# Given the X numpy array, show the elements in reverse position

ab [::-1]

array([43, 27, 10,  6, 41, 49, 32, 21, 24,  2,  4,  2,  7, 34, 28])

In [136]:
# Given the X numpy array, show the elements in an odd position

ab [::2]

array([28,  7,  4, 24, 32, 41, 10, 43])

In [144]:
# Given the X numpy matrix, show the first row elements

ac = np.random.randint (40, size = (4,4))
print (ac)

ac [0]

[[33 23 38  1]
 [ 3  1 17 34]
 [11 38 27 37]
 [14 31  0 32]]


array([33, 23, 38,  1])

In [145]:
# Given the X numpy matrix, show the last row elements

ac [-1]

array([14, 31,  0, 32])

In [147]:
# Given the X numpy matrix, show the first element on first row

ac [0,0]

33

In [148]:
# Given the X numpy matrix, show the last element on last row

ac [-1, -1]

32

In [149]:
# Given the X numpy matrix, show the middle row elements

ac [1:-1]

array([[ 3,  1, 17, 34],
       [11, 38, 27, 37]])

In [154]:
# Given the X numpy matrix, show the first two elements on the first two rows

ac [:2 , :2]

array([[33, 23],
       [ 3,  1]])

In [156]:
# Given the X numpy matrix, show the last two elements on the last two rows

ac [-2: , -2:]

array([[27, 37],
       [ 0, 32]])

<hr style="margin-bottom: 40px;">

### Array manipulation

In [168]:
# Convert the given integer numpy array to float

ba = np.random.randint (1, 60, size = (6))
print (ba)

np.array (ba, np.float)

[ 9 14  3 16 14  6]


array([ 9., 14.,  3., 16., 14.,  6.])

In [171]:
# Reverse the given numpy array (first element becomes last)

bb = np.random.randint (1, 100, size = (6))
print (bb)

bb [::-1]

[44 42 17 61 86 40]


array([40, 86, 61, 17, 42, 44])

In [173]:
# Order (sort) the given numpy array

bc = np.random.randint (1, 100, size = (6))
print (bc)

bc.sort()
print (bc)


[81 97 83 54 15 25]
[15 25 54 81 83 97]


In [175]:
# Given the X numpy array, set the fifth element equal to 1

bd = np.random.randint (10, 100, size = (6))
print (bd)

bd [4] = 1
print (bd)


[71 68 91 75 47 40]
[71 68 91 75  1 40]


In [180]:
# Given the X numpy matrix, change the last row with all 1

X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X [-1:] = 1
print (X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]]


In [189]:
# Given the X numpy matrix, change the last item on the last row with a 0

be = np.ones ((4,4))
print (be)

be [-1,-1] = 0
print (be)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 0.]]


In [195]:
# Given the X numpy matrix, add 5 to every element

bf = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

print (bf)

bf1 = 5 + bf
print (bf1)

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

<hr style="margin-bottom: 40px;">

### Boolean arrays

In [204]:
# Given the X numpy array, get the negative elements

ca = np.array([-1,2,0,-4,5,6,0,0,-9,10])
ca1 = ca [ca<0]
print (ca1)
ca1.sort()
print (ca1)

[-1 -4 -9]
[-9 -4 -1]


In [207]:
# Given the X numpy array, get numbers higher than 5

cb = np.random.randint (-50, 50, size = 10)
print (cb)

cb1 = cb [cb > 5]
print (cb1)

[ 16  41 -29   3   6 -25 -35   8  41  46]
[16 41  6  8 41 46]


In [211]:
# Given the X numpy array, get numbers higher than the elements mean

cc = np.random.randint (0, 50, size = 15)
print (cc)

cc1 = cc [cc > (cc.mean ())]
print (cc1)
print (cc.mean ())

[28  0 27 23 13  0 48 38 15  5  5  9 17 33 17]
[28 27 23 48 38 33]
18.533333333333335


In [221]:
# Given the X numpy array, get numbers equal to 2 or 10

cd = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

cd1 = cd [(cd == 2) | (cd == 10)]
print (cd1)

[ 2 10]


<hr style="margin-bottom: 40px;">

### Logic functions

In [239]:
# Given the X numpy array, return True if none of its elements is zero

ce = np.random.randint (0, 50, size = 15)
print (ce)

ce.all()

# all() retorna true se todos dos elementos do array for difente de zero (que é o mesmo que falso)

[34 13  1 43 15 45 17 12 47 41 38 15 30 26 29]


True

In [230]:
# Given the X numpy array, return True if any of its elements is zero

cf = np.random.randint (0, 50, size = 15)
print (cf)

cf.any()

# any() retorna true se algum dos elementos do array for difente de zero (que é o mesmo que falso)

[18 44 18 43 23  1 27 20 42  1 16 14 31 13 16]


True

<hr style="margin-bottom: 40px;">

### Summary statistics

In [242]:
# Given the X numpy array, show the sum of its elements

da = np.random.randint (0, 50, size = 15)
print (da)

da.sum () 

[37  5 44 33  6 35 34 38 19 48 10 32 46 45 21]


453

In [243]:
# Given the X numpy array, show the mean value of its elements

db = np.random.randint (0, 50, size = 15)
print (db)

db.mean () 

[ 3  5 31 48 25  0 11  5 47 25 15 34 10  5 21]


19.0

In [247]:
# Given the X numpy matrix, show the sum of its columns

de = np.random.randint (0, 50, size = (4,4))
print (de)

de.sum(axis=0)

# axis = 0 -- columns
# axis = 1 -- rows

[[35 11 16 18]
 [31 15  4  4]
 [26 16 23 16]
 [24 43 37 14]]


array([116,  85,  80,  52])

In [249]:
# Given the X numpy matrix, show the mean value of its rows

df = np.random.randint (0, 50, size = (4,4))
print (df)

df.mean(axis=1)

[[13 17 48 20]
 [33 47 41 35]
 [45 41 45 47]
 [25 32  4 42]]


array([24.5 , 39.  , 44.5 , 25.75])

In [250]:
# Given the X numpy array, show the max value of its elements

dg = np.random.randint (0, 50, size = (4,4))
print (dg)

dg.max()

[[ 3 20 13  6]
 [45 43 45 12]
 [26 49 27 14]
 [40 19  8 34]]


49